In [3]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
from sklearn import datasets
from sklearn.svm import SVC


In [7]:
digits=datasets.load_digits()
X=digits.data
y=digits.target


In [8]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,random_state=0)


In [9]:
model=SVC(kernel='linear')
model.fit(Xtrain,ytrain)
ypred=model.predict(Xtest)


In [11]:
from sklearn import metrics
print(metrics.classification_report(ypred,ytest))
print(metrics.confusion_matrix(ypred,ytest))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.98      0.91      0.94        46
           2       1.00      0.98      0.99        45
           3       0.96      0.98      0.97        44
           4       1.00      0.97      0.99        39
           5       0.98      0.98      0.98        48
           6       0.98      1.00      0.99        51
           7       0.98      1.00      0.99        47
           8       0.92      0.94      0.93        47
           9       0.94      0.96      0.95        46

    accuracy                           0.97       450
   macro avg       0.97      0.97      0.97       450
weighted avg       0.97      0.97      0.97       450

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 42  0  0  0  0  1  0  3  0]
 [ 0  0 44  0  0  0  0  0  1  0]
 [ 0  0  0 43  0  0  0  0  0  1]
 [ 0  0  0  0 38  0  0  1  0  0]
 [ 0  0  0  0  0 47  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0